### ISSUE TITLE
This is a great little project...

### ISSUE THREAD

**Issue by lookfirst** [andrepolischuk/magnifier#1]
Thanks! Using this quite a bit. Nice simple es6 code. :+1: 

Need to extend it in two ways...

1. make the size and rounding of the glass configurable. pass in an argument to the constructor?
1. I'm seeing an issue where it doesn't always go away when the mouse is moved off the edge of the image quickly. Maybe add a timeout for when it isn't moving for a certain amount of time and the mouse is not currently over the image?

I'm happy to submit PR's just figured I'd poke your interest first...

**Comment by andrepolischuk** [comment]
Hi, thanks for ideas. I'm open to PR, but I want to specify:

1. Do you think pass only `size` or `height` and `width` separately?
2. I'll think how to do this.

**Comment by lookfirst** [comment]
In the constructor, I'd add an optional `ctx` object to override just these properties default settings...
https://github.com/andrepolischuk/magnifier/blob/master/index.js#L11-L15
and pass in something like this as the `ctx` object so that it is easy to just do a merge on the existing with the override...

```
{
  lens: {
    style: {
      border: '4px solid #eee',
      ...
    }
  }
}
```

**Comment by andrepolischuk** [comment]
I think this way is complicated.

We specify only lens properties. May be we can pass something like:

```js
{
  height: 100,
  width: 100,
  radius: 50,
  background: '#fff',
  borderColor: '#eee',
  borderWidth: 4
}
```

Or I suggest use chaining to override props to simplify creation and code readability:

```js
new Magnifier(element)
  .width(150)
  .radius(75)
  .borderWidth(5);

**Comment by lookfirst** [comment]
Sure... I was approaching this from a code complexity point of view. `this.lens = _.merge(defaults, overrides)` seemed simpler to me than plucking things from a flat properties list. Don't forget about overriding `className`, which is why I suggested the full object structure. 

If you'd like provide a fluent API, that is fine too. Just seemed like more work as well. =)

**Comment by andrepolischuk** [comment]
I think passing props via `ctx` is simpler for us, but complicated for those who will use magnifier.

Will you submit PR about this?

**Comment by lookfirst** [comment]
Sure, but what is the decision? Fluent api or object? :smile:

**Comment by andrepolischuk** [comment]
API

**Comment by lookfirst** [comment]
Any thoughts on my #2 problem? I can reproduce this reliably on your demo page especially by moving the mouse quickly back and forth over the image.

http://take.ms/VXYWK

**Comment by andrepolischuk** [comment]
I fixed #2 problem in d5e665f56d20a79ef2a0260e10abc2a0fc008948

**Comment by lookfirst** [comment]
confirmed. thanks! =) i'll work on the fluent api as soon as i stop fighting some fires in my biz. =)

**Comment by lookfirst** [comment]
I'm still here... just swamped with day job...

**Comment by andrepolischuk** [comment]
Will you add this features or should I add them?

**Comment by lookfirst** [comment]
Sorry. I've added them to my fork but I've been really busy with a new business so I probably won't have time to do a PR for a while. Feel free to take what you want from my fork. I've also done another thing which is to remove the element from the dom.

**Comment by andrepolischuk** [comment]
I added some in 4eebaf8bc8267a5337d0406a707969c58c768c5a
