### ISSUE TITLE
this.onmove.bind() is undefined

### ISSUE THREAD

**Issue by lookfirst** [andrepolischuk/magnifier#2]
seeing this error on some devices (blackberry and sometimes mobile safari 4 and 5)...

TypeError: Result of expression 'this.onmove.bind' [undefined] is not a function.

can we just check to make sure it is defined?

**Comment by andrepolischuk** [comment]
I think it is undefined because [`Function.prototype.bind`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) is not supported in ios safari < 6.0.

I didn't planned to support browsers without ECMAScript 5 support

**Comment by lookfirst** [comment]
Interesting... that explains a lot... no worries... I just have no control over who visits my site so I try to support them the best that I can...

**Comment by lookfirst** [comment]
I just changed the code to this:

    if (this.onmove && this.onmove.bind) {
      this.onmove = this.onmove.bind(this);
      this.onend = this.hide.bind(this);
      this.bind();
    }

**Comment by andrepolischuk** [comment]
You can use [bind polyfill](https://github.com/leahciMic/polyfill-function-prototype-bind) or [ES5 shim](https://github.com/es-shims/es5-shim/blob/master/README.md)

**Comment by lookfirst** [comment]
@andrepolischuk Good point, but the errors seem to be on devices where I just disable the magnifier anyway... =)

**Comment by andrepolischuk** [comment]
Can I close this?
