### ISSUE TITLE
Lens offset wrong if page is scrolled and image inside a fixed container

### ISSUE THREAD

**Issue by nnarhinen** [andrepolischuk/magnifier#3]
If I use magnifier inside a bootstrap modal that has fixed positioning and the page underneath has  scrollY > 0, then the lens has wrong offset. I worked around this now by always scrolling to top when showing the modal and then scrolling back when the modal is hidden but it is not pretty.

**Comment by andrepolischuk** [comment]
Thank for report. I fixed this in andrepolischuk/global-offset#1
